theme: jekyll-theme-minimal
title: Andrew Sverdrup
description: Software dev ğŸ’», basketball ğŸ€, working out ğŸ’ªğŸ». </br></br>andrew@sverdrup.dev
logo: /assets/img/logo.png
show_downloads: false
google_analytics: UA-82637401-4
